### PR TITLE
Add configuration files

### PR DESCRIPTION
**Pull request by rogeruiz**
Some basic configuration files around JavaScript linting and editor
configuration. You can read more about `.editorconfig` files
[here](http://editorconfig.org).

The `.eslintrc.yml` file was generated using `eslint --init` and following the
prompts to look at the current files. I added `no-console: 'off'` to ensure no
errors were thrown when a `console.log( /* */ )` was found.

### CODE REVIEW

**Comment by ungoldman** [comment]
Hi @rogeruiz! Thanks for the PR. Tabby is already using [`standard`](https://github.com/feross/standard) which covers the same things and helps avoid style arguments. It's included in the `package.json` so if you've already run `npm install` you should be able to get the benefits of style and syntax linting just by running `npm test`.

**Comment by rogeruiz** [comment]
@ungoldman Thanks for pointing me in the right direction and sorry about adding this PR without opening an issue first. I didn't take a look at the `package.json` to see that there was a different linter being used.

_Should I open another PR for the `.editorconfig` file_? Or do you think it's not needed? I've found it's helpful working with a base set of line-endings and tab delimiters from the editor perspective, since it overrides your default preferences which can be much more subjective than the ones in any given project.

**Comment by ungoldman** [comment]
I will defer to @maxogden but I don't believe it's needed at this point. I think something like an `.editorconfig` is a personal preference that should be left up to the creator of the project whether or not to include, and it's a little inappropriate to try to impose your style and editor preferences on someone else's project.

**Comment by rogeruiz** [comment]
@ungoldman. Gotcha. Sorry. I had run through the source files to check to make sure if the editor preferences matched the current style of line endings, tabs, etc., but I'm okay with not including it. Thanks!

**Pull request closed without merging**
