### PR TITLE
add app menu, multi-window support

### PR DESCRIPTION
**Pull request by ungoldman**
- using electron menu for shortcuts
- CmdOrCtrl+N now creates new window
- CmdOrCtrl+T now creates new tab
- CmdOrCtrl+Shift+W now closes window
- don't default to fullscreen for new windows (gets annoying)

### CODE REVIEW

**Comment by ungoldman** [comment]
This was fun!

**Comment by ungoldman** [comment]
alternate project codename: spacecat (firefox competitor)

**Comment by emilbayes** [comment]
Or Felix, the first cat in space?

**Comment by max-mapper** [comment]
WOW thanks @ungoldman, best PR I've received all year

**Pull request merged**
